# Generated by Django 3.0.3 on 2020-02-21 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tempdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='eUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=40)),
                ('solar_power', models.FloatField()),
                ('wind_power', models.FloatField()),
                ('time_duration', models.DurationField()),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.organization')),
            ],
        ),
    ]
